//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Education
    {
        public int EmpID { get; set; }
        public string SchoolName { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public Nullable<double> Total { get; set; }
    }
}
